title: My first GitHub site
author: Anna Yegorochkina
email: your-email@domain.com
description: GitHub site
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
